<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{
    $relation_data = getRelation_apiData();
    if(empty($relation_data))
    {
          http_response_code(404);
          $error = [
            "status" => 404,
            "message" => "Data not found"
          ];
          echo json_encode($error);
    }else
    {
        echo json_encode($relation_data);
    }
    exit();
}

