<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST" || $request_method == "GET")
{
   
    $inputData = json_decode(file_get_contents('php://input'),true);
    if(empty($inputData)){
        http_response_code(404);
        echo json_encode([
            'message' => 'Input field was empty'
        ]);
        exit();
    }
    if($inputData['type'] == 'getGraphData'){
        $userId = $inputData['userId'];
        $isUserExist = Wo_UserData($userId);
        if(empty($isUserExist)){
            http_response_code(404);
            $error = [

                "message" => "User was not exist"
            ];
            echo json_encode($error);
            exit();
        }
    
        $result = treeView($userId);
    
        echo json_encode($result);
        exit();
    }elseif($inputData['type'] == 'getSingleGraphData'){
        $userId = $inputData['userId'];
        $isUserExist = Wo_UserData($userId);
        if(empty($isUserExist)){
            http_response_code(404);
            $error = [
       
                "message" => "User was not exist"
            ];
            echo json_encode($error);
            exit();
        }
    
        $result = singleTreeView($userId);
    
        echo json_encode($result);
        exit();
    }

    
}