<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{


    $data_ = array();
    $inputdata = json_decode(file_get_contents("php://input"),true);
    $message = [];
    if(!empty($inputdata)){

        $commentType = $inputdata['commentType'];

        $logged_user = $inputdata['userId'];
        $user_comment = $inputdata['comment'];
        $comment_id = $inputdata['commentId'];
        $post_id = $inputdata['postId'];
        $parentComment = $inputdata['parentComment'];
        $child_comment_id = $inputdata['childComment'];

        //Check user exist
        $isUserExist = Wo_UserData($logged_user);
        
        if(empty($isUserExist)){
            http_response_code(404);
            $error = [
                "status" => 404,
                "message" => "User was not exist"
            ];
            echo json_encode($error);
            exit();
        }

        if($commentType == 'postComment'){

            if(empty($logged_user) && empty($user_comment) && empty($post_id)){
                http_response_code(404);
                $error = [
                    'status' => 404,
                    'message' => 'field was empty'
                ];
                echo json_encode($error);
                exit();
            }
                    
            $result = post_comment($logged_user,$post_id,$user_comment);
           
            if($result){
                echo json_encode($result);
                exit();       
            }
            else{
                http_response_code(404);
                echo json_encode([
                    'status' => 404,
                    'message' => 'Failed to comment'
                ]);
                echo json_encode($result);
                exit();  
            }
        }
        elseif($commentType == 'postChildComment'){
            if(empty($logged_user) && empty($user_comment) && empty($parentComment)){
                http_response_code(404);
                $error = [
                    'status' => 404,
                    'message' => 'field was empty'
                ];
                echo json_encode($error);
                exit();
            }

            $postChildComment = postChildComments($logged_user,$user_comment,$parentComment);

            echo json_encode($postChildComment);
            die();


        }

        elseif($commentType == 'deleteChildComment'){
            if(empty($logged_user) && empty($child_comment_id) && empty($parentComment)){
                http_response_code(404);
                $error = [
                    'status' => 404,
                    'message' => 'field was empty'
                ];
                echo json_encode($error);
                exit();
            }

            $deleteChildComments = deleteChildComments($logged_user,$child_comment_id,$parentComment);

            echo json_encode($deleteChildComments);
            die();


        }
        elseif($commentType == 'deleteComment'){

            if(empty($logged_user) && empty($comment_id) && empty($post_id)){
                http_response_code(404);
                $error = [
                    'status' => 404,
                    'message' => 'field was empty'
                ];
                echo json_encode($error);
                exit();
            }
            $result = delete_comment($logged_user,$post_id,$comment_id);
            
            echo json_encode($result);
            exit();       
            
        }
        elseif($commentType == 'updateComment'){

            if(empty($logged_user) && empty($comment_id) && empty($post_id) && empty($user_comment)){
                http_response_code(404);
                $error = [
                    'status' => 404,
                    'message' => 'field was empty'
                ];
                echo json_encode($error);
                exit();
            }
            $result = updateComment($logged_user,$post_id,$comment_id,$user_comment);
            
            echo json_encode($result);
            exit();       
            
        }
        else{
            http_response_code(404);
            echo json_encode([
                'status' => 404,
                'message' => 'Unknown comment type'
            ]);
            exit();            
        }

    }
    else{
        $data = [
            'status' => 500,
            'message' => 'Data is empty'
        ];
        exit();
    }

}