<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{
    $data_ = array();
    $inputdata = json_decode(file_get_contents("php://input"),true);
    $message = [];
    if(!empty($inputdata)){

        $user_id = $inputdata['userId'];
        $post_id = $inputdata['postId'];
        $page = $inputdata['page'];
        $perPage = $inputdata['perPage'];

        $isPostExist = isPostExist($post_id);

        if(!$isPostExist){
            http_response_code(404);
            $error = [
                "status" => 404,
                "message" => "post was not exist"
            ];
            echo json_encode($error);
            exit();
        } 
        $result = listing_comments($user_id,$post_id,$page,$perPage);

        echo json_encode($result);
        exit();
    }
    else{
        http_response_code(404);
        $data = [
            'status' => 404,
            'message' => 'Data is empty'
        ];
        exit();
    }

}