<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{
if($_POST['postType']=='imageWithContent')
{


$user_id = $_POST['userId'];
$description = $_POST['description'];
$user_name = $_POST['userName'];
$title = $_POST['title'];
$image = $_FILES["image"];


if(!empty($user_id))
{
    $user = is_userid($user_id);
    if($user == 1){
        if (!empty($image["tmp_name"])){

            $fileInfo      = array(
                'file' => $image["tmp_name"],
                'name' => $image['name'],
                'size' => $image["size"],
                'type' => $image["type"],
                'types' => 'jpeg,jpg,png,bmp,gif,tiff,svg,avif,apng,heif,psd,raw,tga',

            );
            
            $media         = Wo_ShareFile($fileInfo);
            $upload_image = $media['filename'];
        
        }
        else{
        http_response_code(404); 
        $error = ['status' => 404,'message' => 'Please Choose the File'];
        echo json_encode($error);exit();
        }
        if(!empty($upload_image))
        {

            $time = time();
            $post_result = add_post_data($user_id,$description,$time,$user_name,$title,$upload_image);
        
                if(!empty($post_result))
                {
                        echo json_encode([
                            'status' => 200,
                            'message' => 'Post uploaded'
                        ]);exit();
                          
                }else{
                    http_response_code(404);    
                    $error = ['status' => 404,'message' => 'Post can\'t upload'];
                    echo json_encode($error);exit();
                }
                        
        }else{
            http_response_code(404);
            $error = ['status' => 404,'message' => 'Please Choose the Image File'];
            echo json_encode($error);exit();
            }
    
    }else{
        http_response_code(404);
        $error = ['status' => 404,'message' => 'Not Register in User'];
        echo json_encode($error);exit();
    }

}else{
    http_response_code(404);
    $error = ['status' => 404,'message' => 'User_id Empty'];
    echo json_encode($error); exit();
}

   

}
elseif ($_POST['postType']=='videoWithContent') {
    
    // echo "video_with_content";
    
$user_id = $_POST['userId'];
$description = $_POST['description'];
$user_name = $_POST['userName'];
$title = $_POST['title'];
$video = $_FILES["video"];


if(!empty($user_id))
{
    $user = is_userid($user_id);
    if($user == 1){
        if (!empty($video["tmp_name"])){

            $fileInfo      = array(
                'file' => $video["tmp_name"],
                'name' => $video['name'],
                'size' => $video["size"],
                'type' => $video["type"],
                'types' => 'mp4,mov,webm,flv,avi,wmv,ogg,m4v,dv,3gp,hdv,iframe,hevc,avchd',

            );
            
            $media         = Wo_ShareFile($fileInfo);
            $upload_video = $media['filename'];
        
        }
        else{
        http_response_code(400);    
        $error = ['status' => 400,'message' => 'Please Choose the File'];
        echo json_encode($error);exit();
        }
        if(!empty($upload_video))
        {
            

            $time = time();
            $post_result = add_post_data($user_id,$description,$time,$user_name,$title,$upload_video);
        
            if(!empty($post_result))
            {
                    echo json_encode([
                        'status' => 200,
                        'message' => 'Video uploaded'
                    ]);exit();
                      
            }else{
                http_response_code(404);    
                $error = ['status' => 404,'message' => 'Video can\'t upload'];
                echo json_encode($error);exit();
            }
        }else{
            http_response_code(404);
            $error = ['status' => 404,'message' => 'Please Choose the Video File'];
            echo json_encode($error);exit();
            }
    
    }else{
        http_response_code(404);
        $error = ['status' => 404,'message' => 'User not exist'];
        echo json_encode($error);exit();
    }

}else{
    http_response_code(404);
    $error = ['status' => 404,'message' => 'User id was Empty'];
    echo json_encode($error); exit();
}


} 
elseif ($_POST['postType']=='audioWithContent') {
    
    // echo "audio_with_content";

    
$user_id = $_POST['userId'];
$description = $_POST['description'];
$user_name = $_POST['userName'];
$title = $_POST['title'];
$audio = $_FILES["audio"];



if(!empty($user_id))
{
    $user = is_userid($user_id);
    if($user == 1){
        if (!empty($audio["tmp_name"])){


            $fileInfo      = array(
                'file' => $audio["tmp_name"],
                'name' => $audio['name'],
                'size' => $audio["size"],
                'type' => $audio["type"],
                'types' => 'mp3,wav,mpeg,aac,aiff,bwf,caf,mp4,rf64',
            );
            
            $media         = Wo_ShareFile($fileInfo);
            $uplad_audio = $media['filename'];

        
        }
        else{
        http_response_code(404);    
        $error = ['status' => 404,'message' => 'Please Choose the File'];
        echo json_encode($error);exit();
        }
        if(!empty($uplad_audio))
        {

            $time = time();
            $post_result = add_post_data($user_id,$description,$time,$user_name,$title,$uplad_audio);
        
                if(!empty($post_result))
                {
                    echo json_encode([
                        'status' => 200,
                        'message' => 'Audio uploaded'
                    ]);exit();
                      
                }else{
                    http_response_code(404);    
                $error = ['status' => 404,'message' => 'Audio can\'t upload'];
                echo json_encode($error);exit();
                }
        }else{
            http_response_code(404);
            $error = ['status' => 404,'message' => 'Please Choose the Video File'];
            echo json_encode($error);exit();
            }
    
    }else{
        http_response_code(404);
        $error = ['status' => 404,'message' => 'User was not exist'];
        echo json_encode($error);exit();
    }

}else{
    http_response_code(404);
    $error = ['status' => 404,'message' => 'User id Empty'];
    echo json_encode($error); exit();
}



}
elseif ($_POST['postType']=='textWithContent') {
    
    // echo "text_with_content";
    
    $user_id = $_POST['userId'];
    $description = $_POST['description'];
    $user_name = $_POST['userName'];
$title = $_POST['title'];
$text = $_POST['text'];

    if(empty($text))
    {
        http_response_code(404);
        $data = array(
            'status' => 404,
            'message' => 'Please Type the Text'
        );
        echo json_encode($data);
        exit();
    }

    $title = Wo_Secure($title);
    $description = Wo_Secure($description);
    $text = Wo_Secure($text);
    

    $post_id = insert_post_text($user_id,$title,$description,$text);
      if (!empty($post_id))
    {
        echo json_encode([
            'status' => 200,
            'message' => 'Text uploaded'
        ]);exit();
          

        echo json_encode($data);
        exit();
    }
    else
    {   http_response_code(404);
        $data = array(
            'status' => 404,
            'message' => 'User Text Upload Faild'
        );
        echo json_encode($data);
        exit();
    }
    

}
else
{   http_response_code(404);
    $data = array(
        'status' => 404,
        'message' => 'Post Type Not Match'
    );
    echo json_encode($data);
    exit();

}
    
}

