<?php

// session_start();

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');



$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{ 

    $data_ = array();
    $phone = 0;
    $inputdata = json_decode(file_get_contents("php://input"),true);

    if(!empty($inputdata)){

    
        $user_id = $inputdata['userId'];
        $isUserExist = Wo_UserData($user_id);

        if(empty($isUserExist)){
            http_response_code(404);
            $error = [
                "status" => 404,
                "message" => "User was not exist"
            ];
            echo json_encode($error);
            exit();
        }


        

        // news api integration....

        $apikey = '02589f92715d5ee3f1760c9516f33743';
        $endpoint = 'http://api.mediastack.com/v1/news';
        $querystring = [
            'access_key' => $apikey,
            'keywords' => 'food industry',
            'categories' => '-entertainment',
            'sort' => 'popularity',
            'languages' => 'en',
        ];

        // https://api.mediastack.com/v1/news?access_key=02589f92715d5ee3f1760c9516f33743&keywords=virus

        $apiurl = $endpoint.'?'. http_build_query($querystring);

        $curl = curl_init($apiurl);

        curl_setopt($curl,CURLOPT_RETURNTRANSFER,true);

        $response = curl_exec($curl);
        curl_close($curl);

        // api result stored in variable
        $apiresult = json_decode($response,true);
        
        
        // pagination remove code 
        unset($apiresult['pagination']);
       
        // 2D formate array convert in - 1D - array formate convert code...
        $onearray = array_reduce($apiresult,'array_merge',[]);

        $newarray = [];
        // default name change in user foreach loop ...
        foreach($onearray as $subarray)
        {
            $newsubarray = [];
            foreach($subarray as $oldkey => $value)
            {
                if ($oldkey === 'author')
                {
                    $newsubarray['username'] = $value;
                }
                elseif($oldkey === 'title')
                {
                    $newsubarray['title'] = $value;
                }
                elseif($oldkey === 'description')
                {
                    $newsubarray['description'] = $value;
                }
                elseif($oldkey === 'url')
                {
                    $newsubarray['url'] = $value;
                }
                elseif($oldkey === 'source')
                {
                    $newsubarray['source'] = $value;
                }
                elseif($oldkey === 'image')
                {
                    $newsubarray['thumbnail'] = $value;
                }
                elseif($oldkey === 'category')
                {
                    $newsubarray['category'] = $value;
                }
                elseif($oldkey === 'language')
                {
                    $newsubarray['language'] = $value;
                }
                elseif($oldkey === 'country')
                {
                    $newsubarray['country'] = $value;
                }
                elseif($oldkey === 'published_at')
                {
                    $newsubarray['uploaded_time'] = $value;
                }
            }
            
            $newarray['posts'][] = $newsubarray;
        }

        // $newarray['posts'] = $newarray;
        

        // user feed empty in execute condition...
        if (empty($newarray)) {
           
            $error = [
                "status" => 404,
                "message" => "News is Empty"
            ];
            echo json_encode($error);
            exit();
        } else{
            echo json_encode($newarray);
            exit();
        }

    }else{
        http_response_code(404);
        $error = [
            "status" => 404,
            "message" => "Input field was empty"
        ];
        echo json_encode($error);
        exit();    
    }
}


