<?php
// session_start();

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');



$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{ 

    $data_ = array();
    $phone = 0;
    $inputdata= json_decode(file_get_contents("php://input"),true);

    if(!empty($inputdata)){

        $user_id = $inputdata['userId'];
        $postId = $inputdata['postId'];

        if(empty($user_id && $postId)){
            http_response_code(404);
            $error = [
                'status' => 404,
                'message' => 'userId or postId was empty'
            ];

            echo json_encode($error);
            exit();
        }

        $isUserExist = Wo_UserData($user_id);

        if(empty($isUserExist)){
            http_response_code(404);
            $error = [
                "status" => 404,
                "message" => "User was not exist"
            ];
            echo json_encode($error);
            exit();
        }

        $isPostExist = isPostExist($postId);

        if(!$isPostExist){
            http_response_code(404);
            $error = [
                "status" => 404,
                "message" => "post was not exist"
            ];
            echo json_encode($error);
            exit();
        }
            
        $user_result = deletePost($user_id,$postId);

         if(empty($user_result))
         {
            $error = [
                        "status" => 404,
                        "message" => "Wrong post"
                    ];
                    echo json_encode($error);
                    exit();
         }else{
            echo json_encode($user_result);
                    exit();
         }



    }else{
        $error = [
            'status' => 404,
            'message' => 'Input field empty'
        ];
        echo json_encode($error);
        exit();
    }


}

