<?php

// session_start();

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');



$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{ 

    $data_ = array();
    $phone = 0;
    $inputdata = json_decode(file_get_contents("php://input"),true);

    if(!empty($inputdata)){

        $user_id = $inputdata['userId'];
        $post_id = $inputdata['postId'];
        $isUserExist = Wo_UserData($user_id);

        if(empty($isUserExist)){
            http_response_code(404);
            $error = [
                "status" => 404,
                "message" => "User was not exist"
            ];
            echo json_encode($error);
            exit();
        }

        $result = singleFeed($user_id,$post_id);

        if(empty($result))
        {
           http_response_code(404);
           $error = [
                       "status" => 404,
                       "message" => "post id was not found"
                   ];
                   echo json_encode($error);
                   exit();
        }else{
           echo json_encode($result);
                   exit();
        }
    }

}