<?php
header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{
    $inputdata = json_decode(file_get_contents("php://input"),true);
    if(!empty($inputdata)){

        $username = $inputdata['userName'];
        $user_id = $inputdata['userId'];
            
        $result = searchUser($username,$user_id);
        
        echo json_encode($result);

        die();
            
        
                
    }else{

        http_response_code(404);
        $error = [
            'status' => 404,
            "message" => "Input was empty"
        ];
        echo json_encode($error);
        exit();
    }

}