<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{
    
    $data_ = array();
    $phone = 0;
    $inputdata = json_decode(file_get_contents("php://input"),true);

    if($inputdata){

        $username = $inputdata['userName'];
        $displayname = $inputdata['displayName'];
        $email        = $inputdata['email'];
        $phone_number = $inputdata['phoneNumber'];
        $password     = $inputdata['password'];
        $country_name   = $inputdata['countryName'];
        settype($phone_number, "string");
        $verify_phone = isValidTelephoneNumber($phone_number);

        if($verify_phone != 1){
            http_response_code(404);
                $errors = [
                'status' => 404,
                'message' =>'phoneNumber is not valid'
                ];
                echo json_encode($errors);
                exit();
        }

        if (empty($username) || empty($displayname) || empty($email) || empty($phone_number) || empty($password) || empty($country_name)) {
            http_response_code(404);

            $errors = [
                'status' => 404,
                'message' => 'Required field was empty'
            ];
            echo json_encode($errors);
            exit();
        } else {
                
                if (Wo_EmailExists($email) === true) {
                    $errors = "User already exists please login";
                }
                
                // if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                //     $errors = $error_icon . $wo['lang']['email_invalid_characters'];
                // }
                // if (strlen($password) < 6) {
                //     $errors = $error_icon . $wo['lang']['password_short'];
                // }

                if (empty($errors)) {
                    $activate = ($wo['config']['emailValidation'] == '1') ? '0' : '1';
                    $code = md5(rand(1111, 9999) . time());
                    $re_data  = array(
                        'email' => Wo_Secure($email, 0),
                        'display_name' => Wo_Secure($displayname, 0),
                        'username' => Wo_Secure($username, 0),
                        'password' => $password,
                        'phone_number' => $phone_number,
                        'country_name' => $country_name,
                        'src' => 'site',
                        'lastseen' => time(),
                        'active' => Wo_Secure($activate),
                    );

        
                    $in_code  = (isset($_GET['invited'])) ? Wo_Secure($_GET['invited']) : false;
                
                    $register = Wo_RegisterUser($re_data,$in_code);
                    
                    echo json_encode($register);
                    exit();
                }
                else{
                        http_response_code(404);
                        $error = [
                            'status' => 404,
                            'message' => $errors
                        ];
                        echo json_encode($error);
                        exit();
                } 
                
        }
    }
}
