<?php


header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{

    $data_ = array();
    $phone = 0;
    $inputdata = json_decode(file_get_contents("php://input"),true);

    if(!empty($inputdata)){
        $follower_number = $inputdata['follower_number'];
        $following_number = $inputdata['following_number'];
        $relation = $inputdata['relation'];
        findUserId($follower_number,$following_number);
    }

}