<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{
    
    $data_ = array();
    $phone = 0;

    $username_list = username_listing();

    if($username_list){
        http_response_code(200);
        $data = [
            'status' => 200,
            'message' => 'success',
            'usersList' => $username_list
        ];
        echo json_encode($data);
        exit();
    }
    else{
        http_response_code(404);
        $data = [
            'status' => 404,
            'message' => 'Something wrong'
        ];
        echo json_encode($data);
        exit();
    }

}
