<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');



$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{
    $data_ = array();
    $inputdata = json_decode(file_get_contents("php://input"),true);
    $message = [];
    if(!empty($inputdata)){

        $like_type = $inputdata['likeType'];
        $logged_user = Wo_Secure($inputdata['userId']);
        $post_user = Wo_Secure($inputdata['postUser']);
        $post_id = Wo_Secure($inputdata['postId']);

        $isPostExist = isPostExist($post_id);

        if(!$isPostExist){
            http_response_code(404);
            $error = [
                "status" => 404,
                "message" => "post was not exist"
            ];
            echo json_encode($error);
            exit();
        } 

        if($like_type == 'like'){

            $liked = like($logged_user,$post_id,$post_user);
            if(!empty($liked)){
                echo json_encode($liked);
                exit(); 
            }else{
                http_response_code(404);
                echo json_encode([
                    'status' => 404,
                    'message' => 'Something wrong'
                ]);
                exit();
            }
        }
        elseif($like_type == 'unlike'){
            $unliked = unlike($logged_user,$post_id);
            if(!empty($unliked)){
                echo json_encode([
                    'status' => 200,
                    'message' => 'Unliked'
                ]);
                exit(); 
            }else{
                http_response_code(404);
                echo json_encode([
                    'status' => 404,
                    'message' => 'Something wrong'
                ]);
                exit();
            }

        }
        else{
            http_response_code(404);
            $error = [
                'status' => 404,
                'message' => 'Unknown like type'
            ];
            echo json_encode($error);
        }

        exit();
    }

}
