<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: GET,POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');



$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{

    $data_ = array();
    $inputdata = json_decode(file_get_contents("php://input"),true);
    $message = [];
    if(!empty($inputdata)){
        $user_id = $inputdata['userId'];
        $post_id = $inputdata['postId'];
        $page = $inputdata['page'];
        $perPage = $inputdata['perPage'];

        $isPostExist = isPostExist($post_id);

        if(!$isPostExist){
            http_response_code(404);
            $error = [
                "status" => 404,
                "message" => "post was not exist"
            ];
            echo json_encode($error);
            exit();
        }
        
        $result = list_of_likes($user_id,$post_id,$page,$perPage);
        if(!empty($result)){
            echo json_encode($result);
        }
        else{
            http_response_code(404);
            echo json_encode([
                'status' => 404,
                'message' => 'Blog id is not exist'
            ]);
        }
        exit();
    }
    else{
        http_response_code(404);
        echo json_encode([
            'status' => 404,
            'message' => 'Input field was empty'
        ]);
        exit();
    }

}