<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');



$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{

    $inputdata = json_decode(file_get_contents("php://input"),true);
    $message = [];

    if(!empty($inputdata)){
        $account_type = $inputdata['Account_type'];
        $user_id = $inputdata['User_id'];
        

    if(empty($user_id))
    {
        http_response_code(404);
        $message = ['status' => 404,'message' => 'User id is Empty'];
        echo json_encode($message);
        exit();
    }
    // user already register or not check code
    $user = is_userid($user_id);

    if($user == 1){
    // user data get in method
    $user_data = Wo_UserData($user_id);

    // private account change in used code's
        if($account_type == 'Private'){
            $privacy = 1;

            if($user_data['confirm_followers'] == 0){
                if($privacy == 1)
                {
                    // private account update funciton
                     $result = Update_privacy_account($user_id,$privacy);

                     if($result == 1)
                     {
                        $message = ['status' => 200,
                        'username' => $user_data['username'],
                        'user_id' => $user_data['user_id'],
                        'message' => 'User Account Private Change Success'];
                        echo json_encode($message);
                        exit();    
                     }

                }
                
            }
            else{
                $message = ['status' => 200,
                'username' => $user_data['username'],
                'user_id' => $user_data['user_id'],
                'message' => 'User Account Private Change Success'];
                echo json_encode($message);
                exit();   
            }
            
        }elseif($account_type == 'Public'){
            $privacy = 0;

            if($user_data['confirm_followers'] == 1){
                
                if($privacy == 0)
                {
                    // private account update funciton
                     $result = Update_privacy_account($user_id,$privacy);

                     if($result == 1)
                     {
                        $message = ['status' => 200,
                        'username' => $user_data['username'],
                        'user_id' => $user_data['user_id'],
                        'message' => 'User Account Public Change Success'];
                        echo json_encode($message);
                        exit();    
                     }

                }
                
            }
            else{
                $message = ['status' => 200,
                'username' => $user_data['username'],
                'user_id' => $user_data['user_id'],
                'message' => 'User Account Public Change Success'];
                echo json_encode($message);
                exit();   
            }
            
        }
        

    }else{
        http_response_code(404);
        $message = ['status' => 404,'message' => 'Not Register in User ID'];
        echo json_encode($message);
        exit();
    }

    }
    
}

