<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{
    $user_id = $_POST['userId'];
    // $description = $_POST['description'];
    // $user_name = $_POST['userName'];
    $title = $_POST['title'];
    
    
    $isUserExist = Wo_UserData($user_id);
        
    if(empty($isUserExist)){
        http_response_code(404);
        $error = [
            "status" => 404,
            "message" => "User was not exist"
        ];
        echo json_encode($error);
        exit();
    }
    if($_POST['storyType']=='imageWithContent')
    {
        $image = $_FILES["image"];
        $media_type = 'photo';
        $fileInfo      = array(
            'file' => $image["tmp_name"],
            'name' => $image['name'],
            'size' => $image["size"],
            'type' => $image["type"],
            'types' => 'jpeg,jpg,png,bmp,gif,tiff,svg,avif,apng,heif,psd,raw,tga',
        );
        
        $media         = Wo_ShareFile($fileInfo);
        $upload_image = $media['filename'];

        if(!empty($upload_image))
        {
            $post_result = insertStory($user_id,$title,$upload_image,$media_type);
            echo json_encode($post_result);die();     
        }else{
            http_response_code(404);
            $error = ['status' => 404,'message' => 'Please Choose the Image File'];
            echo json_encode($error);exit();
        }
    }
    elseif($_POST['storyType']=='videoWithContent'){
        $video = $_FILES["video"];
        $media_type = 'video';
        $fileInfo      = array(
            'file' => $video["tmp_name"],
            'name' => $video['name'],
            'size' => $video["size"],
            'type' => $video["type"],
            'types' => 'mp4,mov,webm,flv,avi,wmv,ogg,m4v,dv,3gp,hdv,iframe,hevc,avchd',

        );
        
        $media         = Wo_ShareFile($fileInfo);
        $upload_video = $media['filename'];

        if(!empty($upload_video))
        {
            $post_result = insertStory($user_id,$title,$upload_video,$media_type);
            echo json_encode($post_result);die();     
        }else{
            http_response_code(404);
            $error = ['status' => 404,'message' => 'Please Choose the Image File'];
            echo json_encode($error);exit();
        }
    }elseif($_POST['storyType']=='audioWithContent'){
        $audio = $_FILES["audio"];
        $media_type = 'audio';
        $fileInfo      = array(
            'file' => $audio["tmp_name"],
            'name' => $audio['name'],
            'size' => $audio["size"],
            'type' => $audio["type"],
            'types' => 'mp3,wav,mpeg,aac,aiff,bwf,caf,mp4,rf64',
        );
        
        $media         = Wo_ShareFile($fileInfo);
        $upload_audio = $media['filename'];
        if(!empty($upload_audio))
        {
            $post_result = insertStory($user_id,$title,$upload_audio,$media_type);
            echo json_encode($post_result);die();     
        }else{
            http_response_code(404);
            $error = ['status' => 404,'message' => 'Please Choose the Image File'];
            echo json_encode($error);exit();
        }
    }

}