<?php
// http://localhost/onefamily/updateprofileapi   --server api url

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{

    $userImage = $_FILES["userImage"];
    $coverImage = $_FILES["coverImage"];
    $userId = $_POST['userId'];

    $isUserExist = Wo_UserData($userId);

    if(empty($isUserExist)){
        http_response_code(404);
        $error = [
            "status" => 404,
            "message" => "User was not exist"
        ];
        echo json_encode($error);
        exit();
    }

    $coverimage = $coverImage['name'];
    if(empty($coverimage)){
        $uploadCoverImage = 'empty';
    }else{
        $userCoverImage = array(
            'file' => $coverImage["tmp_name"],
            'name' => $coverImage['name'],
            'size' => $coverImage["size"],
            'type' => $coverImage["type"],
            'types' => 'jpeg,jpg,png,bmp,gif,tiff,svg,avif,apng,heif,psd,raw,tga',
        );
        
        $coverMedia         = Wo_ShareFile($userCoverImage);
        $uploadCoverImage = $coverMedia['filename'];
    }

    $userimage = $userImage['name'];
    if(empty($userimage)){
        $uploadUserImage = 'empty';
    }else{
        $userImageInfo = array(
        'file' => $userImage["tmp_name"],
        'name' => $userImage['name'],
        'size' => $userImage["size"],
        'type' => $userImage["type"],
        'types' => 'jpeg,jpg,png,bmp,gif,tiff,svg,avif,apng,heif,psd,raw,tga',
        );    
        $userMedia         = Wo_ShareFile($userImageInfo);
        $uploadUserImage   = $userMedia['filename'];
    }

    if($uploadUserImage == 'empty' && $uploadCoverImage == 'empty'){
        http_response_code(404);
        echo json_encode([
            'status' => 404,
            'message' => 'Please choose image'
        ]
        );
        die();
    }

    $uploadImage = uploadImage($uploadCoverImage,$uploadUserImage,$userId);

    if($uploadImage){
        echo json_encode($uploadImage);
        die();
    }else{
        http_response_code(404);
        echo json_encode([
            'status' => 404,
            'message' => 'Image can\'t uploaded'
        ]
        );
        die();
    }
}