<?php

header('Access-Control-Allow-Origin:*');
header('Content-type: application/json; charset=utf-8');
header('Access-Control-Allow-Method: POST');
header('Access-Control-Allow-Headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Request-With');

$request_method = $_SERVER['REQUEST_METHOD'];
if($request_method == "POST")
{
    $inputdata = json_decode(file_get_contents("php://input"),true);
    if($inputdata['otp-type'] == 'two_step_verification'){
        if(!empty($inputdata)){
            $email = Wo_Secure($inputdata['email']);
            $sendMail = sendMail($email);
            if($sendMail[0]){
                $message = [
                    'message' => 'success'
                ];
            }
            else{
                $message = [
                    'message' => 'Mail not sent successfully'
                ];
            }
            if($message['message'] == 'success'){
                $verification_code = $sendMail[1];
                $result = insert_verification_code($verification_code);
                if($result){
                    $message = [
                        'status' => 200,
                        'message' => $message['message']
                    ];
                    echo json_encode($message);
                    exit();
                }
            }  
            else{
                    http_response_code(500);
                    $message = [
                        'status' => 500,
                        'message'=>$message['message']
                    ];
                    echo json_encode($message);
                    exit();
                }
        }
        else{
            http_response_code(400);
            $error = [
                'status' => 400,
                'message' => 'Data empty'
            ];
            echo json_encode($error);
            exit();
        }
    }

}